# POST http://localhost:3000/tasks
# Content-Type: application/json
# Accept: application/json

# {"title": "some title baz", "description": "task ddd baz"}

HTTP/1.1 201 Created
X-Powered-By: Express
Content-Type: application/json; charset=utf-8
Content-Length: 78
ETag: W/"4e-mCU980yOPoHOn00UIjxApq11Nl4"
Date: Wed, 24 Jul 2019 07:05:06 GMT
Connection: close

{
  "description": "task ddd baz",
  "title": "some title baz",
  "status": "OPEN",
  "id": 3
}
