### GET /tasks/id
# GET http://localhost:3000/tasks/94df7a50-a873-11e9-822c-3ffb140ed45ds

HTTP/1.1 404 Not Found
X-Powered-By: Express
Content-Type: application/json; charset=utf-8
Content-Length: 71
ETag: W/"47-EZr3CGIMyROvSf2CUXraJzyEa74"
Date: Wed, 17 Jul 2019 09:20:10 GMT
Connection: close

{
  "statusCode":404,
  "error":"Not Found",
  "message":"Task does not exists"
}
