
# GET http://localhost:3000
# HTTP/1.1 200 OK
# X-Powered-By: Express
# Content-Type: text/html; charset=utf-8
# Content-Length: 12
# ETag: W/"c-Lve95gjOVATpfV8EL5X4nxwjKHE"
# Date: Sun, 14 Jul 2019 13:38:41 GMT
# Connection: close

# Hello World!


//
// GET ALL TASKS
//
### GET /tasks
GET http://localhost:3000/tasks
# HTTP/1.1 200 OK
# X-Powered-By: Express
# Content-Type: application/json; charset=utf-8
# Content-Length: 2
# ETag: W/"2-l9Fw4VUO7kr8CvBlt4zaMCqXZ0w"
# Date: Sun, 14 Jul 2019 13:41:48 GMT
# Connection: close

# []


//
// GET (@Query tasks) ALL TASKS by search string
//
// @body GetTasksFilterDTO
### GET /tasks
# GET http://localhost:3000/tasks?search=task---
# GET http://localhost:3000/tasks?search=foo&status=OPEN
# GET http://localhost:3000/tasks?search=foo--
GET http://localhost:3000/tasks?status=CLOSED
# GET http://localhost:3000/tasks?search=task---&status=OPEN


//
// GET A TASK BY ID
//
### GET /tasks/id
GET http://localhost:3000/tasks/c430c330-a879-11e9-a83f-2f717802ed7ed

# HTTP/1.1 200 OK
# X-Powered-By: Express
# Content-Type: application/json; charset=utf-8
# Content-Length: 124
# ETag: W/"7c-wW8RbAqk7/jfi3QgRg/r74ndJeM"
# Date: Sun, 14 Jul 2019 17:50:48 GMT
# Connection: close

# {
#   "description": "task 4 description",
#   "title": "some title task 4",
#   "id": "d82afa70-a65f-11e9-bf33-1ba7ec4a593a",
#   "status": "OPEN"
# }


//
// CREATE A TASK
//
### POST /tasks
POST http://localhost:3000/tasks
Content-Type: application/json
Accept: application/json

{"title": "some title baz-- task 444", "description": "task 444 description"}

# HTTP/1.1 201 Created
# X-Powered-By: Express
# Content-Type: application/json; charset=utf-8
# Content-Length: 124
# ETag: W/"7c-0Jp3b84pl9EO4OVy+W3c4GvDzp0"
# Date: Sun, 14 Jul 2019 15:31:29 GMT
# Connection: close

# {
#   "description": "task 1 description",
#   "title": "some title task 1",
#   "id": "73934f30-a64c-11e9-accb-b7a5975ab41c",
#   "status": "OPEN"
# }



//
// UPDATE TASK STATUS
//
### PATCH /tasks/id/status
PATCH http://localhost:3000/tasks/e2a6eb50-a879-11e9-a83f-2f717802ed7ed/status
Content-Type: application/json

{ "status": "OPEN" }

# HTTP/1.1 200 OK
# X-Powered-By: Express
# Content-Type: application/json; charset=utf-8
# Content-Length: 128
# ETag: W/"80-J9/wCwQPF0yXTTbSdtPil90hU00"
# Date: Tue, 16 Jul 2019 12:21:29 GMT
# Connection: close

# {
#   "description": "task 11 description",
#   "title": "some title task 11",
#   "id": "25276c40-a7c4-11e9-85d1-c728967e4ccb",
#   "status": "CLOSED"
# }


//
// DELETE A TASK
//
### DELETE /tasks
DELETE  http://localhost:3000/tasks/b13faf30-a87d-11e9-bfb1-df58e26acd24
